require('dotenv').config({ path: '../backend/.env' });
const mongoose = require('mongoose');
const Assessment = require('../backend/models/Assessment');

async function testDB() {
    try {
        console.log("Connecting to MongoDB...");
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected successfully!");

        const dummyData = new Assessment({
            skills: "React, Node.js, AI",
            interests: "Full Stack AI Developer",
            analysis: "This is a test analysis generated by the AI agent to verify MongoDB connection.",
            recommendations: [
                { role: "AI Engineer", match: "99%", roadmap: "/ai-engineer" }
            ]
        });

        await dummyData.save();
        console.log("Dummy data saved successfully! Check your MongoDB Dashboard now.");
        
    } catch (error) {
        console.error("Error:", error);
    } finally {
        mongoose.connection.close();
    }
}

testDB();
